#!/usr/bin/env bash

LOCALS_NAME=${LOCALS_NAME:-'.local-aliases'}

function __locals_parse_aliases_names() {
  sed -n 's/^alias \([^=]*\)=.*/\1/p' "$1"
}

function __locals_info() {
  printf "$(tput setaf 8)%s " "$1"
  mapfile -t < <(__locals_parse_aliases_names "$2")
  printf "$(tput bold)%s$(tput sgr0)\n" "${MAPFILE[*]}"
}

function __locals_load() {
  if [[ -f "$LOCALS_NAME" ]]; then
    . "$LOCALS_NAME"
    [[ -n "$LOCALS_VERBOSE" ]] && __locals_info "local" "$LOCALS_NAME"
  fi
}

function __locals_on_enter() {
  local prev_aliases="$OLDPWD/$LOCALS_NAME"
  if [[ -f "$prev_aliases" ]] ; then
    for key in $(__locals_parse_aliases_names "$prev_aliases"); do
      unalias "$key" > /dev/null 2>&1
    done
    [[ -n "$LOCALS_DEBUG" ]] && __locals_info "unalias" "$prev_aliases"
  fi
  __locals_load
  [[ -n "$LOCALS_HOOK" ]] && "$LOCALS_HOOK"
}

function cd() {
  builtin cd "$@" || exit
  __locals_on_enter
}

function locals() {
  [[ -n "$EDITOR" ]] && "$EDITOR" "$LOCALS_NAME" && __locals_on_enter
}

alias locals-refresh=__locals_on_enter
__locals_load

# vim: ft=sh

